### PR TITLE
fix: Correct the composite-query

### PR DESCRIPTION
**Pull request by bdfinst**
The CVE Counts by Package and Flavor query did not report Unicorn packages because of a misspelling and the fact that there were no vulnerabilities. It should show the Unicorn packages even if there are no vulnerabilities.

### CODE REVIEW

**Review by naveensrinivasan — APPROVED** [review]
Thank you @bdfinst

**Comment by naveensrinivasan** [comment]
Thank you @bdfinst. I am going to cherry-pick your commit and merge it.

**Comment by partkyle** [comment]
@naveensrinivasan I looked and this is the query that we are running in the looker studio now, save for some formatting differences. 

Can we close or merge this PR to resolve it?

**Comment by naveensrinivasan** [comment]
> @naveensrinivasan I looked and this is the query that we are running in the looker studio now, save for some formatting differences.
> 
> Can we close or merge this PR to resolve it?

I am not able to merge because `e2e` doesn't run without write access.

**Pull request merged**
